"""Revamp schema for Phase 1 Foundation

Revision ID: 5e52520e65b3
Revises: 038171b2dbb3
Create Date: 2026-04-10 07:50:08.795827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e52520e65b3'
down_revision: Union[str, Sequence[str], None] = '038171b2dbb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_errors',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('probability_percent', sa.Float(), nullable=True),
    sa.Column('recovery_time_minutes', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_errors_id'), 'task_errors', ['id'], unique=False)
    op.add_column('blockers', sa.Column('probability_percent', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('interface_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('active_touch_time_minutes', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('machine_wait_time_minutes', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('shadow_it_used', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('shadow_it_link', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('source_data', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('output_format_example', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('post_task_verification', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('risks_yield_scrap', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('tribal_knowledge', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('media', sa.JSON(), nullable=True))
    op.drop_column('tasks', 'error_probability')
    op.drop_column('tasks', 'tat_minutes')
    op.drop_column('tasks', 'potential_mistakes')
    op.drop_column('tasks', 'recovery_time_minutes')
    op.add_column('workflows', sa.Column('version', sa.String(), nullable=True))
    op.add_column('workflows', sa.Column('tool_family', sa.String(), nullable=True))
    op.add_column('workflows', sa.Column('involves_equipment', sa.Boolean(), nullable=True))
    op.add_column('workflows', sa.Column('equipment_state', sa.String(), nullable=True))
    op.add_column('workflows', sa.Column('cleanroom_execution_required', sa.Boolean(), nullable=True))
    op.add_column('workflows', sa.Column('yield_risk', sa.Boolean(), nullable=True))
    op.add_column('workflows', sa.Column('flow_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'flow_summary')
    op.drop_column('workflows', 'yield_risk')
    op.drop_column('workflows', 'cleanroom_execution_required')
    op.drop_column('workflows', 'equipment_state')
    op.drop_column('workflows', 'involves_equipment')
    op.drop_column('workflows', 'tool_family')
    op.drop_column('workflows', 'version')
    op.add_column('tasks', sa.Column('recovery_time_minutes', sa.FLOAT(), nullable=True))
    op.add_column('tasks', sa.Column('potential_mistakes', sa.TEXT(), nullable=True))
    op.add_column('tasks', sa.Column('tat_minutes', sa.FLOAT(), nullable=True))
    op.add_column('tasks', sa.Column('error_probability', sa.FLOAT(), nullable=True))
    op.drop_column('tasks', 'media')
    op.drop_column('tasks', 'tribal_knowledge')
    op.drop_column('tasks', 'risks_yield_scrap')
    op.drop_column('tasks', 'post_task_verification')
    op.drop_column('tasks', 'output_format_example')
    op.drop_column('tasks', 'source_data')
    op.drop_column('tasks', 'shadow_it_link')
    op.drop_column('tasks', 'shadow_it_used')
    op.drop_column('tasks', 'machine_wait_time_minutes')
    op.drop_column('tasks', 'active_touch_time_minutes')
    op.drop_column('tasks', 'interface_type')
    op.drop_column('blockers', 'probability_percent')
    op.drop_index(op.f('ix_task_errors_id'), table_name='task_errors')
    op.drop_table('task_errors')
    # ### end Alembic commands ###
