"""rename occurrences to occurrence

Revision ID: 919e2c751328
Revises: de06fb4cb634
Create Date: 2026-04-20 09:54:47.631206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919e2c751328'
down_revision: Union[str, Sequence[str], None] = 'de06fb4cb634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('occurrence', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('occurrence_explanation', sa.Text(), nullable=True))
    op.drop_column('tasks', 'occurrences_per_cycle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('occurrences_per_cycle', sa.INTEGER(), nullable=True))
    op.drop_column('tasks', 'occurrence_explanation')
    op.drop_column('tasks', 'occurrence')
    # ### end Alembic commands ###
