"""add system parameters

Revision ID: a9bd9d021d1b
Revises: 5e52520e65b3
Create Date: 2026-04-10 09:14:33.067154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bd9d021d1b'
down_revision: Union[str, Sequence[str], None] = '5e52520e65b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_parameters',
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=True),
    sa.Column('manual_values', sa.JSON(), nullable=True),
    sa.Column('python_code', sa.Text(), nullable=True),
    sa.Column('last_executed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cached_values', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_parameters_id'), 'system_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_system_parameters_key'), 'system_parameters', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_parameters_key'), table_name='system_parameters')
    op.drop_index(op.f('ix_system_parameters_id'), table_name='system_parameters')
    op.drop_table('system_parameters')
    # ### end Alembic commands ###
