"""add discrepancy tracking and parameter logs

Revision ID: aae64aab9ddc
Revises: a9bd9d021d1b
Create Date: 2026-04-10 13:37:21.329654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae64aab9ddc'
down_revision: Union[str, Sequence[str], None] = 'a9bd9d021d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_parameters', sa.Column('pending_values', sa.JSON(), nullable=True))
    op.add_column('system_parameters', sa.Column('has_discrepancy', sa.Boolean(), nullable=True))
    op.add_column('workflows', sa.Column('cadence_count', sa.Float(), nullable=True))
    op.add_column('workflows', sa.Column('cadence_unit', sa.String(), nullable=True))
    op.drop_column('workflows', 'frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('frequency', sa.FLOAT(), nullable=True))
    op.drop_column('workflows', 'cadence_unit')
    op.drop_column('workflows', 'cadence_count')
    op.drop_column('system_parameters', 'has_discrepancy')
    op.drop_column('system_parameters', 'pending_values')
    # ### end Alembic commands ###
