"""initial_schema_v3

Revision ID: de06fb4cb634
Revises: 
Create Date: 2026-04-20 09:42:16.538677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de06fb4cb634'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_key', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('found_values', sa.JSON(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameter_logs_parameter_key'), 'parameter_logs', ['parameter_key'], unique=False)
    op.create_table('system_parameters',
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=True),
    sa.Column('manual_values', sa.JSON(), nullable=True),
    sa.Column('python_code', sa.Text(), nullable=True),
    sa.Column('last_executed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cached_values', sa.JSON(), nullable=True),
    sa.Column('pending_values', sa.JSON(), nullable=True),
    sa.Column('has_discrepancy', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_parameters_id'), 'system_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_system_parameters_key'), 'system_parameters', ['key'], unique=True)
    op.create_table('taxonomy_enums',
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_taxonomy_enums_category'), 'taxonomy_enums', ['category'], unique=False)
    op.create_index(op.f('ix_taxonomy_enums_id'), 'taxonomy_enums', ['id'], unique=False)
    op.create_index(op.f('ix_taxonomy_enums_label'), 'taxonomy_enums', ['label'], unique=False)
    op.create_table('workflows',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('prc', sa.String(), nullable=True),
    sa.Column('workflow_type', sa.String(), nullable=True),
    sa.Column('tool_family', sa.String(), nullable=True),
    sa.Column('tool_family_count', sa.Integer(), nullable=True),
    sa.Column('tool_id', sa.String(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('poc', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('trigger_description', sa.Text(), nullable=True),
    sa.Column('cadence_count', sa.Float(), nullable=True),
    sa.Column('cadence_unit', sa.String(), nullable=True),
    sa.Column('output_type', sa.String(), nullable=True),
    sa.Column('output_description', sa.Text(), nullable=True),
    sa.Column('repeatability_check', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('flow_summary', sa.Text(), nullable=True),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('total_roi_saved_hours', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=False)
    op.create_table('tasks',
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_system', sa.String(), nullable=True),
    sa.Column('interface_type', sa.String(), nullable=True),
    sa.Column('interface', sa.String(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('tool_id', sa.String(), nullable=True),
    sa.Column('hardware_family', sa.String(), nullable=True),
    sa.Column('trigger_architecture', sa.String(), nullable=True),
    sa.Column('output_classification', sa.String(), nullable=True),
    sa.Column('active_touch_time_minutes', sa.Float(), nullable=True),
    sa.Column('machine_wait_time_minutes', sa.Float(), nullable=True),
    sa.Column('automation_time_minutes', sa.Float(), nullable=True),
    sa.Column('manual_time_minutes', sa.Float(), nullable=True),
    sa.Column('occurrences_per_cycle', sa.Integer(), nullable=True),
    sa.Column('owning_team', sa.String(), nullable=True),
    sa.Column('owner_positions', sa.JSON(), nullable=True),
    sa.Column('shadow_it_used', sa.Boolean(), nullable=True),
    sa.Column('shadow_it_link', sa.String(), nullable=True),
    sa.Column('source_data', sa.Text(), nullable=True),
    sa.Column('source_data_list', sa.JSON(), nullable=True),
    sa.Column('output_data_list', sa.JSON(), nullable=True),
    sa.Column('output_format_example', sa.Text(), nullable=True),
    sa.Column('post_task_verification', sa.Text(), nullable=True),
    sa.Column('verification_steps', sa.JSON(), nullable=True),
    sa.Column('validation_needed', sa.Boolean(), nullable=True),
    sa.Column('validation_procedure', sa.Text(), nullable=True),
    sa.Column('risks_yield_scrap', sa.Boolean(), nullable=True),
    sa.Column('tribal_knowledge', sa.JSON(), nullable=True),
    sa.Column('tribal_knowledge_list', sa.JSON(), nullable=True),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('reference_links', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('blockers',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('blocking_entity', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('probability_percent', sa.Float(), nullable=True),
    sa.Column('average_delay_minutes', sa.Float(), nullable=True),
    sa.Column('standard_mitigation', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockers_id'), 'blockers', ['id'], unique=False)
    op.create_table('task_errors',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('probability_percent', sa.Float(), nullable=True),
    sa.Column('recovery_time_minutes', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_errors_id'), 'task_errors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_errors_id'), table_name='task_errors')
    op.drop_table('task_errors')
    op.drop_index(op.f('ix_blockers_id'), table_name='blockers')
    op.drop_table('blockers')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_taxonomy_enums_label'), table_name='taxonomy_enums')
    op.drop_index(op.f('ix_taxonomy_enums_id'), table_name='taxonomy_enums')
    op.drop_index(op.f('ix_taxonomy_enums_category'), table_name='taxonomy_enums')
    op.drop_table('taxonomy_enums')
    op.drop_index(op.f('ix_system_parameters_key'), table_name='system_parameters')
    op.drop_index(op.f('ix_system_parameters_id'), table_name='system_parameters')
    op.drop_table('system_parameters')
    op.drop_index(op.f('ix_parameter_logs_parameter_key'), table_name='parameter_logs')
    op.drop_table('parameter_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
